#!/usr/bin/python
##
# Manualmatic Pendant component for LinuxCNC.
#
# Sets up hal, linuxcnc, creates the Manualmatic helper class instance
# then connects to the Manulamatic Pendant over the USB PORT and starts 
# the poll()ing of the linuscnc user space interface.
#
# GPLv2 Licence https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt
# 
# Copyright (c) 2022 Philip Fletcher <philip.fletcher@stutchbury.com>
# 
##

import sys
import time
import hal
import linuxcnc

from Manualmatic import Manualmatic

PORT='/dev/ttyACM0'


c = hal.component("manualmatic")

c.newpin("estop-is-activated", hal.HAL_BIT, hal.HAL_OUT)

mm = Manualmatic(linuxcnc, c)

while True:
  if (not mm.isRunning()):
    try:
      mm.connect(PORT)
      #mm.init(0.04) #run as a thread  
      if ( not hal.component_is_ready("manualmatic") ):
        c.ready()
      mm.start(0.04) #-OR- as no thread

    except(KeyboardInterrupt):
      mm.stop()
      sys.exit(1)

    except Exception as e:
      print("Exception in manualmatic component")
      print(e)
      raise
      sys.exit(1)

  time.sleep(0.1)
